language: rust
cache: cargo
sudo: false

before_script:
  - (cargo install rustfmt || true)

script:
  - export PATH=$PATH:~/.cargo/bin && cargo fmt -- --write-mode=diff
  - cargo build
  - cargo test
